export const GRADIENT_VARIANTS: Record<string, string> = {
  bug: 'from-bug to-bug/50',
  dark: 'from-dark to-dark/50',
  dragon: 'from-dragon to-dragon/50',
  electric: 'from-electric to-electric/50',
  fairy: 'from-fairy to-fairy/50',
  fighting: 'from-fighting to-fighting/50',
  fire: 'from-fire to-fire/50',
  flying: 'from-flying to-flying/50',
  ghost: 'from-ghost to-ghost/50',
  grass: 'from-grass to-grass/50',
  ground: 'from-ground to-ground/50',
  ice: 'from-ice to-ice/50',
  normal: 'from-normal to-normal/50',
  poison: 'from-poison to-poison/50',
  psychic: 'from-psychic to-psychic/50',
  rock: 'from-rock to-rock/50',
  steel: 'from-steel to-steel/50',
  water: 'from-water to-water/50',
};
